# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05cc46326e3e70f295825696c1c6cdff8ee731997437ecf3614e45f4b3d459d3482f67a8469013241bb45ff5fe661ac3b5dcb8482e6b399e084ed21bff2a755d

test:
  secret_key_base: 1e2d5c090cce37977478d345ee199b2ece24c8eeef4f2cfaa620bf7010d416ee0c709d376f25ee43e777ed7f341eab1712b88ff23b170bbaea64f7449d9d04a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
