# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc154cf3fa98d3c86e0ea0efb98e92cbfd26d6f6b80d3b49c26b3e047b33f93c1b1473691dd5ad6748659d9486d4ed76e35f6457bc0f85365aac3702d9e43d37

test:
  secret_key_base: dd64c82290c883f8bf278afaf47d90a23989dad54246c17245ffc70e4e79371c77e20c7ff827da28e4cb627a3387f20df8895c0d6a87a93d9d65623908611219

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
