# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72705cb0a641005090448b6f5c3944a54d012d8333f89acdda676ca1ac2f1dc3362591c852d946752e248ead1c93b84c73f32b82ca7a6e4ee019a241a2ef1f4b

test:
  secret_key_base: 6bd8042fcd12feffdb44aa40d2b55658c692a24c377f7e6ddc5398a0984fc49df04b67dc4b0c3e4039867c0fc61b603f503f79e983aea7805a99ff95d6bb807e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
