# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59ab97dab7a7e2d8398be6b25c6ad05c28442351a564070aa790bf326eb79d692aa06814b40b31ad31c73d3aca15ae342c37f762e03ec907524d04d438655fda

test:
  secret_key_base: 7d1f2896c6841e7ea9b85d0b4e4afba69260567d53531c852c57847cfd922f23d2cd7c9069018b6db843a516dd8f050658b92ce990702037bfe22546dd7d932b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
