# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99b93beb6320fd694d358d64931c3e7e528cdf02d7106c561ef2dfaf9d62460e02fca1955a986f1a5ef8304c81b02799059efecdf9ed79b4b993f685f20347aa

test:
  secret_key_base: 56ad5868d67543d5f274e8e12a8f03fc2f4e0eeb9b87780461c344495829767c2a88b7f10c0fb3f04c6c3ab245e3b507c90b3b5728405f3ed6979f745476623a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
