# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1859c4067dab12de052e1ed6e252e069de92964eb33fa9f7602618637c121fea70b31f72e3f384d24cf2b8418dfdcd47ed185a8f170b4726ff2653bb8aefec93

test:
  secret_key_base: 1a3647ce61c83950c21c55ffbe0982ee668650a8bcfa05a25ffd8a8fe68d9ca7dc1345d735b6257cf10f79c5f3cc8a0baea39fa5a40909d5c352efcd8485ac90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
