# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c84d607c77c3a237f0da5047ae643377278a8930cfcddbd76ba85aa60f5c739bb539a4de16c36954c8ffc7d5d84b4de9e6e1d15eb1a0313168bacf5fc81bb88

test:
  secret_key_base: adf0fa5885ba6cb74ec426035f8e62b3c243bc360369e88846697a0b6a74a2d871bfb18f971a0a2c2a23bca4f768e66b70949175be5c9879d03d313e66dc36a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
