# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9da833b77b40fd0aaa8c293099540e088cb1ba999992713c2f49ce96afe744e727140f39030bd2b24fb4754c9fc1e0ecd91a940fbf38006cf4ad29d329247464

test:
  secret_key_base: 296df2ed7e96b27352a8a9b09e70af042173e0b84676d1ac4a10d0beeb95c4d9e17d98bb96f61d4ae1d75f6240e6ea4daae022ac945a881e48764bcfe0dbb66b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
