# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37b81590f07561df3c093eaff72b37c34078392d9569de7dc42c89224d672b065d47d359df99ea23a93025aa93d0d12d6001e20013c3b97642c76b43fad2f7f8

test:
  secret_key_base: c3fa33a154ee4eda8aa471f6788882a26d9518760c23301a06c6bb1d851dd33a67c66400c4b9c404fa99d3df6ae211015b8c90994f47b889bea6e85d57bcf190

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
